-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.promocion
(
    promocion_id serial NOT NULL,
    vertical character varying(100) COLLATE pg_catalog."default" NOT NULL,
    mes_promo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    campus character varying(100) COLLATE pg_catalog."default" NOT NULL,
    modalidad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha date NOT NULL,
    CONSTRAINT promocion_pkey PRIMARY KEY (promocion_id)
);

CREATE TABLE IF NOT EXISTS public.claustro_promocion
(
    empleadoid integer NOT NULL,
    promocion_id integer NOT NULL,
    CONSTRAINT claustro_promocion_pkey PRIMARY KEY (empleadoid, promocion_id)
);

CREATE TABLE IF NOT EXISTS public.claustro
(
    empleadoid serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT claustro_pkey PRIMARY KEY (empleadoid)
);

CREATE TABLE IF NOT EXISTS public.alumnos
(
    alumnos_id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    promocion_id integer,
    CONSTRAINT alumnos_pkey PRIMARY KEY (alumnos_id)
);

CREATE TABLE IF NOT EXISTS public.notas
(
    notas_id serial NOT NULL,
    notas text COLLATE pg_catalog."default" NOT NULL,
    alumnos_id integer,
    proyecto_id integer,
    CONSTRAINT notas_pkey PRIMARY KEY (notas_id)
);

CREATE TABLE IF NOT EXISTS public.proyectos
(
    proyecto_id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT proyectos_pkey PRIMARY KEY (proyecto_id)
);

ALTER TABLE IF EXISTS public.claustro_promocion
    ADD CONSTRAINT claustro_promocion_empleadoid_fkey FOREIGN KEY (empleadoid)
    REFERENCES public.claustro (empleadoid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.claustro_promocion
    ADD CONSTRAINT claustro_promocion_promocion_id_fkey FOREIGN KEY (promocion_id)
    REFERENCES public.promocion (promocion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.alumnos
    ADD CONSTRAINT fk_alumnos_promocion FOREIGN KEY (promocion_id)
    REFERENCES public.promocion (promocion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notas
    ADD CONSTRAINT fk_alumnos_id FOREIGN KEY (alumnos_id)
    REFERENCES public.alumnos (alumnos_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notas
    ADD CONSTRAINT fk_proyecto_id FOREIGN KEY (proyecto_id)
    REFERENCES public.proyectos (proyecto_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;